export interface CountryConfig {
  code: string;
  name: string;
  flag: string;
  currency: {
    code: string;
    symbol: string;
    decimals: number;
  };
  tax: {
    name: string; // ITBIS, IVA, IGV, ISV, ITBMS
    defaultRate: number;
  };
  doc: {
    label: string; // RNC, RFC, NIT, RUC, RUT, etc.
    placeholder: string;
    description: string;
  };
  phonePrefix: string;
  phonePlaceholder: string;
  regionsLabel: string; // Provincias, Departamentos, Estados, etc.
  regions: string[];
  hasFiscalEcf: boolean; // Solo para RD (DGII e-CF)
}

export const COUNTRIES: CountryConfig[] = [
  {
    code: "DO",
    name: "República Dominicana",
    flag: "🇩🇴",
    currency: { code: "DOP", symbol: "RD$", decimals: 2 },
    tax: { name: "ITBIS", defaultRate: 18 },
    doc: {
      label: "RNC",
      placeholder: "Ej: 133-19090-7",
      description: "Registro Nacional de Contribuyentes ante la DGII",
    },
    phonePrefix: "+1",
    phonePlaceholder: "(809) 000-0000",
    regionsLabel: "Provincias",
    hasFiscalEcf: true,
    regions: [
      "Distrito Nacional",
      "Santo Domingo",
      "Santiago",
      "Azua",
      "Baoruco",
      "Barahona",
      "Dajabón",
      "Duarte",
      "Elías Piña",
      "El Seibo",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "María Trinidad Sánchez",
      "Monseñor Nouel",
      "Montecristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samaná",
      "San Cristóbal",
      "San José de Ocoa",
      "San Juan",
      "San Pedro de Macorís",
      "Sánchez Ramírez",
      "Santiago Rodríguez",
      "Valverde",
    ],
  },
  {
    code: "MX",
    name: "México",
    flag: "🇲🇽",
    currency: { code: "MXN", symbol: "$", decimals: 2 },
    tax: { name: "IVA", defaultRate: 16 },
    doc: {
      label: "RFC",
      placeholder: "Ej: LAPA891012AB1 o KLY2001019A8",
      description: "Registro Federal de Contribuyentes",
    },
    phonePrefix: "+52",
    phonePlaceholder: "55 1234 5678",
    regionsLabel: "Estados",
    hasFiscalEcf: false,
    regions: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Ciudad de México",
      "Coahuila",
      "Colima",
      "Durango",
      "Estado de México",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    currency: { code: "COP", symbol: "$", decimals: 0 },
    tax: { name: "IVA", defaultRate: 19 },
    doc: {
      label: "NIT",
      placeholder: "Ej: 900.123.456-7",
      description: "Número de Identificación Tributaria",
    },
    phonePrefix: "+57",
    phonePlaceholder: "300 123 4567",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "Bogotá D.C.",
      "Antioquia",
      "Valle del Cauca",
      "Cundinamarca",
      "Santander",
      "Atlántico",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Cesar",
      "Córdoba",
      "Huila",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Quindío",
      "Risaralda",
      "Sucre",
      "Tolima",
      "Amazonas",
      "Arauca",
      "Caquetá",
      "Casanare",
      "Chocó",
      "Guainía",
      "Guaviare",
      "La Guajira",
      "Putumayo",
      "San Andrés y Providencia",
      "Vaupés",
      "Vichada",
    ],
  },
  {
    code: "PA",
    name: "Panamá",
    flag: "🇵🇦",
    currency: { code: "USD", symbol: "$", decimals: 2 },
    tax: { name: "ITBMS", defaultRate: 7 },
    doc: {
      label: "RUC",
      placeholder: "Ej: 155123456-2-2020 DV 12",
      description: "Registro Único de Contribuyente",
    },
    phonePrefix: "+507",
    phonePlaceholder: "6123-4567",
    regionsLabel: "Provincias",
    hasFiscalEcf: false,
    regions: [
      "Panamá",
      "Panamá Oeste",
      "Chiriquí",
      "Colón",
      "Coclé",
      "Veraguas",
      "Herrera",
      "Los Santos",
      "Bocas del Toro",
      "Darién",
      "Guna Yala",
      "Emberá-Wounaan",
      "Ngäbe-Buglé",
    ],
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    currency: { code: "CRC", symbol: "₡", decimals: 2 },
    tax: { name: "IVA", defaultRate: 13 },
    doc: {
      label: "NIF",
      placeholder: "Ej: 3-101-123456",
      description: "Número de Identificación Fiscal",
    },
    phonePrefix: "+506",
    phonePlaceholder: "8123 4567",
    regionsLabel: "Provincias",
    hasFiscalEcf: false,
    regions: [
      "San José",
      "Alajuela",
      "Cartago",
      "Heredia",
      "Guanacaste",
      "Puntarenas",
      "Limón",
    ],
  },
  {
    code: "PE",
    name: "Perú",
    flag: "🇵🇪",
    currency: { code: "PEN", symbol: "S/.", decimals: 2 },
    tax: { name: "IGV", defaultRate: 18 },
    doc: {
      label: "RUC",
      placeholder: "Ej: 20123456789",
      description: "Registro Único de Contribuyentes (SUNAT)",
    },
    phonePrefix: "+51",
    phonePlaceholder: "912 345 678",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "Lima",
      "Arequipa",
      "La Libertad",
      "Piura",
      "Cusco",
      "Lambayeque",
      "Junín",
      "Áncash",
      "Ica",
      "Callao",
      "San Martín",
      "Cajamarca",
      "Loreto",
      "Puno",
      "Ucayali",
      "Tacna",
      "Huánuco",
      "Ayacucho",
      "Amazonas",
      "Apurímac",
      "Huancavelica",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Tumbes",
    ],
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    currency: { code: "CLP", symbol: "$", decimals: 0 },
    tax: { name: "IVA", defaultRate: 19 },
    doc: {
      label: "RUT",
      placeholder: "Ej: 76.123.456-K",
      description: "Rol Único Tributario (SII)",
    },
    phonePrefix: "+56",
    phonePlaceholder: "9 1234 5678",
    regionsLabel: "Regiones",
    hasFiscalEcf: false,
    regions: [
      "Metropolitana de Santiago",
      "Valparaíso",
      "Biobío",
      "La Araucanía",
      "Antofagasta",
      "Coquimbo",
      "Maule",
      "O'Higgins",
      "Los Lagos",
      "Tarapacá",
      "Atacama",
      "Ñuble",
      "Los Ríos",
      "Arica y Parinacota",
      "Aysén",
      "Magallanes y Antártica Chilena",
    ],
  },
  {
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    currency: { code: "USD", symbol: "$", decimals: 2 },
    tax: { name: "IVA", defaultRate: 15 },
    doc: {
      label: "RUC",
      placeholder: "Ej: 1790012345001",
      description: "Registro Único de Contribuyentes (SRI)",
    },
    phonePrefix: "+593",
    phonePlaceholder: "99 123 4567",
    regionsLabel: "Provincias",
    hasFiscalEcf: false,
    regions: [
      "Pichincha",
      "Guayas",
      "Azuay",
      "Manabí",
      "El Oro",
      "Tungurahua",
      "Loja",
      "Santo Domingo de los Tsáchilas",
      "Imbabura",
      "Cotopaxi",
      "Los Ríos",
      "Chimborazo",
      "Esmeraldas",
      "Santa Elena",
      "Cañar",
      "Carchi",
      "Bolívar",
      "Sucumbíos",
      "Orellana",
      "Napo",
      "Pastaza",
      "Morona Santiago",
      "Zamora Chinchipe",
      "Galápagos",
    ],
  },
  {
    code: "ES",
    name: "España",
    flag: "🇪🇸",
    currency: { code: "EUR", symbol: "€", decimals: 2 },
    tax: { name: "IVA", defaultRate: 21 },
    doc: {
      label: "NIF / CIF",
      placeholder: "Ej: B12345678",
      description: "Número de Identificación Fiscal",
    },
    phonePrefix: "+34",
    phonePlaceholder: "612 34 56 78",
    regionsLabel: "Provincias",
    hasFiscalEcf: false,
    regions: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Sevilla",
      "Alicante",
      "Málaga",
      "Murcia",
      "Cádiz",
      "Baleares",
      "Las Palmas",
      "Vizcaya",
      "La Coruña",
      "Santa Cruz de Tenerife",
      "Asturias",
      "Zaragoza",
      "Pontevedra",
      "Granada",
      "Tarragona",
      "Córdoba",
      "Gerona",
      "Guipúzcoa",
      "Toledo",
      "Almería",
      "Badajoz",
      "Jaén",
      "Navarra",
      "Castellón",
      "Cantabria",
      "Valladolid",
      "Ciudad Real",
      "Huelva",
      "León",
      "Lérida",
      "Cáceres",
      "Albacete",
      "Burgos",
      "Salamanca",
      "Lugo",
      "Álava",
      "La Rioja",
      "Orense",
      "Guadalajara",
      "Huesca",
      "Cuenca",
      "Zamora",
      "Palencia",
      "Ávila",
      "Segovia",
      "Teruel",
      "Soria",
    ],
  },
  {
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    currency: { code: "GTQ", symbol: "Q", decimals: 2 },
    tax: { name: "IVA", defaultRate: 12 },
    doc: {
      label: "NIT",
      placeholder: "Ej: 1234567-8",
      description: "Número de Identificación Tributaria (SAT)",
    },
    phonePrefix: "+502",
    phonePlaceholder: "5123 4567",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "Guatemala",
      "Quetzaltenango",
      "Escuintla",
      "Alta Verapaz",
      "San Marcos",
      "Huehuetenango",
      "Sacatepéquez",
      "Chimaltenango",
      "Suchitepéquez",
      "Petén",
      "Quiché",
      "Izabal",
      "Santa Rosa",
      "Retalhuleu",
      "Jalapa",
      "Jutiapa",
      "Zacapa",
      "Chiquimula",
      "Totonicapán",
      "Baja Verapaz",
      "El Progreso",
      "Sololá",
    ],
  },
  {
    code: "HN",
    name: "Honduras",
    flag: "🇭🇳",
    currency: { code: "HNL", symbol: "L", decimals: 2 },
    tax: { name: "ISV", defaultRate: 15 },
    doc: {
      label: "RTN",
      placeholder: "Ej: 08011990123456",
      description: "Registro Tributario Nacional (SAR)",
    },
    phonePrefix: "+504",
    phonePlaceholder: "9123-4567",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "Francisco Morazán",
      "Cortés",
      "Atlántida",
      "Yoro",
      "Comayagua",
      "Choluteca",
      "El Paraíso",
      "Copán",
      "Olancho",
      "Santa Bárbara",
      "Colón",
      "La Paz",
      "Valle",
      "Intibucá",
      "Lempira",
      "Ocotepeque",
      "Islas de la Bahía",
      "Gracias a Dios",
    ],
  },
  {
    code: "SV",
    name: "El Salvador",
    flag: "🇸🇻",
    currency: { code: "USD", symbol: "$", decimals: 2 },
    tax: { name: "IVA", defaultRate: 13 },
    doc: {
      label: "NIT / NRC",
      placeholder: "Ej: 0614-010190-101-1",
      description: "Número de Registro de Contribuyente",
    },
    phonePrefix: "+503",
    phonePlaceholder: "7123 4567",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "San Salvador",
      "La Libertad",
      "Santa Ana",
      "San Miguel",
      "Sonsonate",
      "Usulután",
      "Ahuachapán",
      "La Paz",
      "La Unión",
      "Cuscatlán",
      "Chalatenango",
      "Morazán",
      "San Vicente",
      "Cabañas",
    ],
  },
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    currency: { code: "UYU", symbol: "$", decimals: 2 },
    tax: { name: "IVA", defaultRate: 22 },
    doc: {
      label: "RUT",
      placeholder: "Ej: 219991230015",
      description: "Registro Único Tributario (DGI)",
    },
    phonePrefix: "+598",
    phonePlaceholder: "099 123 456",
    regionsLabel: "Departamentos",
    hasFiscalEcf: false,
    regions: [
      "Montevideo",
      "Canelones",
      "Maldonado",
      "Salto",
      "Paysandú",
      "Colonia",
      "San José",
      "Rivera",
      "Tacuarembó",
      "Cerro Largo",
      "Soriano",
      "Artigas",
      "Rocha",
      "Florida",
      "Lavalleja",
      "Durazno",
      "Río Negro",
      "Treinta y Tres",
      "Flores",
    ],
  },
];

export const DEFAULT_COUNTRY_CODE = "DO";

export function getCountry(code?: string | null): CountryConfig {
  if (!code) return COUNTRIES[0];
  const found = COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found || COUNTRIES[0];
}

export const getCountryByCode = getCountry;
export const LATAM_COUNTRIES = COUNTRIES;
