import { COUNTRIES, type CountryConfig } from "@/lib/countries";

export interface CountryDemoData {
  code: string;
  name: string;
  flag: string;
  currencySymbol: string;
  currencyCode: string;
  taxName: string;
  taxRate: number;
  docLabel: string;
  docPlaceholder: string;
  docSample: string;
  fiscalType: string;
  regulatoryBody: string;
  phonePrefix: string;
  phoneSample: string;
  laundryName: string;
  addressSample: string;
  currencyDecimals: number;
  items: { name: string; price: number; detail?: string }[];
  prices: {
    basico: { monthly: number; yearly: number; display: string };
    pro: { monthly: number; yearly: number; display: string };
    empresa: { monthly: number; yearly: number; display: string };
  };
}

export const COUNTRY_DEMO_DATA: Record<string, CountryDemoData> = {
  DO: {
    code: "DO",
    name: "República Dominicana",
    flag: "🇩🇴",
    currencySymbol: "RD$",
    currencyCode: "DOP",
    taxName: "ITBIS",
    taxRate: 18,
    docLabel: "RNC",
    docPlaceholder: "131-12345-6",
    docSample: "131-12345-6",
    fiscalType: "NCF: B0200000123 (e-CF)",
    regulatoryBody: "DGII (e-CF Comprobantes Fiscales)",
    phonePrefix: "+1",
    phoneSample: "(809) 555-0142",
    laundryName: "Lavandería San Carlos",
    addressSample: "Av. 27 de Febrero, Santo Domingo",
    currencyDecimals: 2,
    items: [
      { name: "Camisa almidonada x2", price: 300, detail: "Lavado y planchado fino" },
      { name: "Pantalón de vestir x1", price: 200, detail: "Planchado a vapor" },
      { name: "Lavado por libra 3.5 lb", price: 280, detail: "Detergente premium + suavizante" },
    ],
    prices: {
      basico: { monthly: 2500, yearly: 25000, display: "RD$ 2,500" },
      pro: { monthly: 4500, yearly: 45000, display: "RD$ 4,500" },
      empresa: { monthly: 7500, yearly: 75000, display: "RD$ 7,500" },
    },
  },
  MX: {
    code: "MX",
    name: "México",
    flag: "🇲🇽",
    currencySymbol: "$",
    currencyCode: "MXN",
    taxName: "IVA",
    taxRate: 16,
    docLabel: "RFC",
    docPlaceholder: "LAPA891012AB1",
    docSample: "LAPA891012AB1",
    fiscalType: "CFDI 4.0 · Folio: MX-0842",
    regulatoryBody: "SAT (Factura Electrónica e IVA)",
    phonePrefix: "+52",
    phoneSample: "55 4123 5678",
    laundryName: "Tintorería & Lavandería La Moderna",
    addressSample: "Col. Del Valle, Ciudad de México",
    currencyDecimals: 2,
    items: [
      { name: "Camisa planchada x2", price: 90, detail: "Lavado y planchaduría" },
      { name: "Pantalón de vestir x1", price: 60, detail: "Planchado profesional" },
      { name: "Lavado por kilo 2.5 kg", price: 85, detail: "Ciclo delicado ecológico" },
    ],
    prices: {
      basico: { monthly: 750, yearly: 7500, display: "$750 MXN" },
      pro: { monthly: 1350, yearly: 13500, display: "$1,350 MXN" },
      empresa: { monthly: 2250, yearly: 22500, display: "$2,250 MXN" },
    },
  },
  CO: {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    currencySymbol: "$",
    currencyCode: "COP",
    taxName: "IVA",
    taxRate: 19,
    docLabel: "NIT",
    docPlaceholder: "900.123.456-7",
    docSample: "900.123.456-7",
    fiscalType: "Factura Electrónica: FE-4921",
    regulatoryBody: "DIAN (Régimen Fiscal Colombiano)",
    phonePrefix: "+57",
    phoneSample: "300 456 7890",
    laundryName: "AquaClean Lavandería Express",
    addressSample: "El Poblado, Medellín, Antioquia",
    currencyDecimals: 0,
    items: [
      { name: "Camisa tintorería x2", price: 18000, detail: "Lavado en seco y planchado" },
      { name: "Pantalón sastre x1", price: 12000, detail: "Planchado al vapor" },
      { name: "Kilo de ropa 3 kg", price: 15000, detail: "Lavado y doblado por peso" },
    ],
    prices: {
      basico: { monthly: 160000, yearly: 1600000, display: "$160.000 COP" },
      pro: { monthly: 290000, yearly: 2900000, display: "$290.000 COP" },
      empresa: { monthly: 480000, yearly: 4800000, display: "$480.000 COP" },
    },
  },
  PA: {
    code: "PA",
    name: "Panamá",
    flag: "🇵🇦",
    currencySymbol: "$",
    currencyCode: "USD",
    taxName: "ITBMS",
    taxRate: 7,
    docLabel: "RUC",
    docPlaceholder: "155123456-2-2020 DV 12",
    docSample: "155123456-2-2020 DV 12",
    fiscalType: "Factura Fiscal: FF-0321",
    regulatoryBody: "DGI Panamá (Factura Electrónica)",
    phonePrefix: "+507",
    phoneSample: "6123-4567",
    laundryName: "Wash & Go Balboa",
    addressSample: "San Francisco, Ciudad de Panamá",
    currencyDecimals: 2,
    items: [
      { name: "Camisa lisa x2", price: 5.0, detail: "Lavado y planchado vapor" },
      { name: "Pantalón vestir x1", price: 4.0, detail: "Cuidado delicado" },
      { name: "Lavado por libra 4 lb", price: 6.0, detail: "Ciclo rápido con suavizante" },
    ],
    prices: {
      basico: { monthly: 39, yearly: 390, display: "$39 USD" },
      pro: { monthly: 69, yearly: 690, display: "$69 USD" },
      empresa: { monthly: 119, yearly: 1190, display: "$119 USD" },
    },
  },
  CR: {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    currencySymbol: "₡",
    currencyCode: "CRC",
    taxName: "IVA",
    taxRate: 13,
    docLabel: "NIF",
    docPlaceholder: "3-101-123456",
    docSample: "3-101-123456",
    fiscalType: "Tiquete Electrónico: TE-0012",
    regulatoryBody: "Ministerio de Hacienda (DGT)",
    phonePrefix: "+506",
    phoneSample: "8123 4567",
    laundryName: "Lavandería Pura Vida",
    addressSample: "Escazú, San José",
    currencyDecimals: 0,
    items: [
      { name: "Camisas x2", price: 3500, detail: "Lavado y planchado" },
      { name: "Pantalón x1", price: 2500, detail: "Planchado a vapor" },
      { name: "Lavado por kilo 2 kg", price: 3200, detail: "Servicio completo" },
    ],
    prices: {
      basico: { monthly: 22000, yearly: 220000, display: "₡ 22.000 CRC" },
      pro: { monthly: 39000, yearly: 390000, display: "₡ 39.000 CRC" },
      empresa: { monthly: 65000, yearly: 650000, display: "₡ 65.000 CRC" },
    },
  },
  PE: {
    code: "PE",
    name: "Perú",
    flag: "🇵🇪",
    currencySymbol: "S/.",
    currencyCode: "PEN",
    taxName: "IGV",
    taxRate: 18,
    docLabel: "RUC",
    docPlaceholder: "20123456789",
    docSample: "20123456789",
    fiscalType: "Boleta Electrónica: B001-0034",
    regulatoryBody: "SUNAT (Comprobante Electrónico)",
    phonePrefix: "+51",
    phoneSample: "912 345 678",
    laundryName: "Lavandería San Isidro Express",
    addressSample: "Miraflores, Lima",
    currencyDecimals: 2,
    items: [
      { name: "Camisa lavado & planchado x2", price: 18.0, detail: "Almidonado ligero" },
      { name: "Pantalón sastre x1", price: 14.0, detail: "Vaporizado profesional" },
      { name: "Lavado al peso 2.5 kg", price: 16.0, detail: "Doblado y empaque" },
    ],
    prices: {
      basico: { monthly: 145, yearly: 1450, display: "S/. 145 PEN" },
      pro: { monthly: 260, yearly: 2600, display: "S/. 260 PEN" },
      empresa: { monthly: 440, yearly: 4400, display: "S/. 440 PEN" },
    },
  },
  CL: {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    currencySymbol: "$",
    currencyCode: "CLP",
    taxName: "IVA",
    taxRate: 19,
    docLabel: "RUT",
    docPlaceholder: "76.123.456-K",
    docSample: "76.123.456-K",
    fiscalType: "Boleta Electrónica: BE-7812",
    regulatoryBody: "SII (Servicio de Impuestos Internos)",
    phonePrefix: "+56",
    phoneSample: "9 1234 5678",
    laundryName: "Tintorería Providencia",
    addressSample: "Las Condes, Santiago de Chile",
    currencyDecimals: 0,
    items: [
      { name: "Camisas planchadas x2", price: 4500, detail: "Almidonado suave" },
      { name: "Pantalón x1", price: 3200, detail: "Planchado a vapor" },
      { name: "Kilo de ropa 2 kg", price: 4200, detail: "Lavado y doblado" },
    ],
    prices: {
      basico: { monthly: 38000, yearly: 380000, display: "$38.000 CLP" },
      pro: { monthly: 68000, yearly: 680000, display: "$68.000 CLP" },
      empresa: { monthly: 115000, yearly: 1150000, display: "$115.000 CLP" },
    },
  },
  EC: {
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    currencySymbol: "$",
    currencyCode: "USD",
    taxName: "IVA",
    taxRate: 15,
    docLabel: "RUC",
    docPlaceholder: "1790012345001",
    docSample: "1790012345001",
    fiscalType: "Factura Electrónica: FE-0012",
    regulatoryBody: "SRI (Servicio de Rentas Internas)",
    phonePrefix: "+593",
    phoneSample: "99 123 4567",
    laundryName: "Lavandería & Tintorería Los Andes",
    addressSample: "La Carolina, Quito",
    currencyDecimals: 2,
    items: [
      { name: "Camisas tintorería x2", price: 5.0, detail: "Planchado al vapor" },
      { name: "Pantalón x1", price: 4.0, detail: "Acabado impecable" },
      { name: "Lavado por peso 3 lb", price: 5.5, detail: "Detergente biodegradable" },
    ],
    prices: {
      basico: { monthly: 39, yearly: 390, display: "$39 USD" },
      pro: { monthly: 69, yearly: 690, display: "$69 USD" },
      empresa: { monthly: 119, yearly: 1190, display: "$119 USD" },
    },
  },
  ES: {
    code: "ES",
    name: "España",
    flag: "🇪🇸",
    currencySymbol: "€",
    currencyCode: "EUR",
    taxName: "IVA",
    taxRate: 21,
    docLabel: "NIF / CIF",
    docPlaceholder: "B12345678",
    docSample: "B12345678",
    fiscalType: "Factura Simplificada: TS-2026-104",
    regulatoryBody: "Agencia Tributaria (AEAT / Veri*factu)",
    phonePrefix: "+34",
    phoneSample: "612 34 56 78",
    laundryName: "Tintorería y Lavandería El Sol",
    addressSample: "Barrio de Salamanca, Madrid",
    currencyDecimals: 2,
    items: [
      { name: "Camisas lavado y planchado x2", price: 5.5, detail: "Planchado artesanal" },
      { name: "Pantalón vestir x1", price: 4.5, detail: "Vaporizado y raya marcada" },
      { name: "Colada por peso 3 kg", price: 5.0, detail: "Lavado, secado y doblado" },
    ],
    prices: {
      basico: { monthly: 39, yearly: 390, display: "39 € EUR" },
      pro: { monthly: 69, yearly: 690, display: "69 € EUR" },
      empresa: { monthly: 119, yearly: 1190, display: "119 € EUR" },
    },
  },
  GT: {
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    currencySymbol: "Q",
    currencyCode: "GTQ",
    taxName: "IVA",
    taxRate: 12,
    docLabel: "NIT",
    docPlaceholder: "1234567-8",
    docSample: "1234567-8",
    fiscalType: "Factura Electrónica FEL: DTE-0982",
    regulatoryBody: "SAT Guatemala (Régimen FEL)",
    phonePrefix: "+502",
    phoneSample: "5123 4567",
    laundryName: "Lavandería Quetzal Real",
    addressSample: "Zona 10, Ciudad de Guatemala",
    currencyDecimals: 2,
    items: [
      { name: "Camisas x2", price: 40.0, detail: "Lavado y planchado" },
      { name: "Pantalón x1", price: 30.0, detail: "Planchado fino" },
      { name: "Lavado por libra 3.5 lb", price: 35.0, detail: "Cuidado de prendas" },
    ],
    prices: {
      basico: { monthly: 310, yearly: 3100, display: "Q 310 GTQ" },
      pro: { monthly: 550, yearly: 5500, display: "Q 550 GTQ" },
      empresa: { monthly: 940, yearly: 9400, display: "Q 940 GTQ" },
    },
  },
  HN: {
    code: "HN",
    name: "Honduras",
    flag: "🇭🇳",
    currencySymbol: "L",
    currencyCode: "HNL",
    taxName: "ISV",
    taxRate: 15,
    docLabel: "RTN",
    docPlaceholder: "08011990123456",
    docSample: "08011990123456",
    fiscalType: "Factura Fiscal: SAR-0031",
    regulatoryBody: "SAR Honduras (Facturación Digital)",
    phonePrefix: "+504",
    phoneSample: "9123-4567",
    laundryName: "Lavandería Central Morazán",
    addressSample: "Colonia Palmira, Tegucigalpa",
    currencyDecimals: 2,
    items: [
      { name: "Camisas x2", price: 120.0, detail: "Lavado y planchado al vapor" },
      { name: "Pantalón x1", price: 95.0, detail: "Acabado profesional" },
      { name: "Lavado por libra 3.5 lb", price: 110.0, detail: "Secado y doblado" },
    ],
    prices: {
      basico: { monthly: 960, yearly: 9600, display: "L 960 HNL" },
      pro: { monthly: 1700, yearly: 17000, display: "L 1,700 HNL" },
      empresa: { monthly: 2900, yearly: 29000, display: "L 2,900 HNL" },
    },
  },
  SV: {
    code: "SV",
    name: "El Salvador",
    flag: "🇸🇻",
    currencySymbol: "$",
    currencyCode: "USD",
    taxName: "IVA",
    taxRate: 13,
    docLabel: "NIT / NRC",
    docPlaceholder: "0614-010190-101-1",
    docSample: "0614-010190-101-1",
    fiscalType: "DTE Electrónico: DTE-5012",
    regulatoryBody: "Ministerio de Hacienda (DTE El Salvador)",
    phonePrefix: "+503",
    phoneSample: "7123 4567",
    laundryName: "Lavandería San Salvador",
    addressSample: "Santa Elena, Antiguo Cuscatlán",
    currencyDecimals: 2,
    items: [
      { name: "Camisas x2", price: 5.0, detail: "Lavado y planchado rápido" },
      { name: "Pantalón x1", price: 4.0, detail: "Planchado profesional" },
      { name: "Lavado por libra 3.5 lb", price: 5.5, detail: "Suavizante aromático" },
    ],
    prices: {
      basico: { monthly: 39, yearly: 390, display: "$39 USD" },
      pro: { monthly: 69, yearly: 690, display: "$69 USD" },
      empresa: { monthly: 119, yearly: 1190, display: "$119 USD" },
    },
  },
  UY: {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    currencySymbol: "$",
    currencyCode: "UYU",
    taxName: "IVA",
    taxRate: 22,
    docLabel: "RUT",
    docPlaceholder: "219991230015",
    docSample: "219991230015",
    fiscalType: "e-Factura CFE: CFE-1092",
    regulatoryBody: "DGI Uruguay (Régimen CFE)",
    phonePrefix: "+598",
    phoneSample: "099 123 456",
    laundryName: "Lavandería Punta Carretas",
    addressSample: "Pocitos, Montevideo",
    currencyDecimals: 2,
    items: [
      { name: "Camisas planchadas x2", price: 220.0, detail: "Planchaduría artesanal" },
      { name: "Pantalón sastre x1", price: 180.0, detail: "Tratamiento de lana" },
      { name: "Kilo de ropa 2 kg", price: 200.0, detail: "Lavado y doblado en paquete" },
    ],
    prices: {
      basico: { monthly: 1550, yearly: 15500, display: "$1,550 UYU" },
      pro: { monthly: 2750, yearly: 27500, display: "$2,750 UYU" },
      empresa: { monthly: 4700, yearly: 47000, display: "$4,700 UYU" },
    },
  },
};

export function getCountryDemo(code?: string): CountryDemoData {
  if (!code) return COUNTRY_DEMO_DATA.DO;
  return COUNTRY_DEMO_DATA[code.toUpperCase()] || COUNTRY_DEMO_DATA.DO;
}
