/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SoftwareLavanderiaSantoDomingoRouteImport } from './routes/software-lavanderia-santo-domingo'
import { Route as SoftwareLavanderiaSantiagoRouteImport } from './routes/software-lavanderia-santiago'
import { Route as SoftwareLavanderiaPuntaCanaRouteImport } from './routes/software-lavanderia-punta-cana'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as NuevaSucursalRouteImport } from './routes/nueva-sucursal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DescargarRouteImport } from './routes/descargar'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugReportesRouteImport } from './routes/t.$slug.reportes'
import { Route as TSlugProcesosRouteImport } from './routes/t.$slug.procesos'
import { Route as TSlugPersonalRouteImport } from './routes/t.$slug.personal'
import { Route as TSlugOrdenesRouteImport } from './routes/t.$slug.ordenes'
import { Route as TSlugNuevaOrdenRouteImport } from './routes/t.$slug.nueva-orden'
import { Route as TSlugLogisticaRouteImport } from './routes/t.$slug.logistica'
import { Route as TSlugLoginRouteImport } from './routes/t.$slug.login'
import { Route as TSlugGastosRouteImport } from './routes/t.$slug.gastos'
import { Route as TSlugFiscalHomologacionRouteImport } from './routes/t.$slug.fiscal-homologacion'
import { Route as TSlugCxcRouteImport } from './routes/t.$slug.cxc'
import { Route as TSlugConversationsRouteImport } from './routes/t.$slug.conversations'
import { Route as TSlugConfiguracionRouteImport } from './routes/t.$slug.configuracion'
import { Route as TSlugClientesRouteImport } from './routes/t.$slug.clientes'
import { Route as TSlugCatalogoRouteImport } from './routes/t.$slug.catalogo'
import { Route as TSlugCajaRouteImport } from './routes/t.$slug.caja'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareLavanderiaSantoDomingoRoute =
  SoftwareLavanderiaSantoDomingoRouteImport.update({
    id: '/software-lavanderia-santo-domingo',
    path: '/software-lavanderia-santo-domingo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoftwareLavanderiaSantiagoRoute =
  SoftwareLavanderiaSantiagoRouteImport.update({
    id: '/software-lavanderia-santiago',
    path: '/software-lavanderia-santiago',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoftwareLavanderiaPuntaCanaRoute =
  SoftwareLavanderiaPuntaCanaRouteImport.update({
    id: '/software-lavanderia-punta-cana',
    path: '/software-lavanderia-punta-cana',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaSucursalRoute = NuevaSucursalRouteImport.update({
  id: '/nueva-sucursal',
  path: '/nueva-sucursal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargarRoute = DescargarRouteImport.update({
  id: '/descargar',
  path: '/descargar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugReportesRoute = TSlugReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugProcesosRoute = TSlugProcesosRouteImport.update({
  id: '/procesos',
  path: '/procesos',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPersonalRoute = TSlugPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugOrdenesRoute = TSlugOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugNuevaOrdenRoute = TSlugNuevaOrdenRouteImport.update({
  id: '/nueva-orden',
  path: '/nueva-orden',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLogisticaRoute = TSlugLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLoginRoute = TSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugGastosRoute = TSlugGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFiscalHomologacionRoute = TSlugFiscalHomologacionRouteImport.update({
  id: '/fiscal-homologacion',
  path: '/fiscal-homologacion',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCxcRoute = TSlugCxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugConversationsRoute = TSlugConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugConfiguracionRoute = TSlugConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugClientesRoute = TSlugClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCatalogoRoute = TSlugCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCajaRoute = TSlugCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/descargar': typeof DescargarRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/software-lavanderia-punta-cana': typeof SoftwareLavanderiaPuntaCanaRoute
  '/software-lavanderia-santiago': typeof SoftwareLavanderiaSantiagoRoute
  '/software-lavanderia-santo-domingo': typeof SoftwareLavanderiaSantoDomingoRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/conversations': typeof TSlugConversationsRoute
  '/t/$slug/cxc': typeof TSlugCxcRoute
  '/t/$slug/fiscal-homologacion': typeof TSlugFiscalHomologacionRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/logistica': typeof TSlugLogisticaRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/procesos': typeof TSlugProcesosRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/descargar': typeof DescargarRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/software-lavanderia-punta-cana': typeof SoftwareLavanderiaPuntaCanaRoute
  '/software-lavanderia-santiago': typeof SoftwareLavanderiaSantiagoRoute
  '/software-lavanderia-santo-domingo': typeof SoftwareLavanderiaSantoDomingoRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/conversations': typeof TSlugConversationsRoute
  '/t/$slug/cxc': typeof TSlugCxcRoute
  '/t/$slug/fiscal-homologacion': typeof TSlugFiscalHomologacionRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/logistica': typeof TSlugLogisticaRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/procesos': typeof TSlugProcesosRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug': typeof TSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/descargar': typeof DescargarRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/software-lavanderia-punta-cana': typeof SoftwareLavanderiaPuntaCanaRoute
  '/software-lavanderia-santiago': typeof SoftwareLavanderiaSantiagoRoute
  '/software-lavanderia-santo-domingo': typeof SoftwareLavanderiaSantoDomingoRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/conversations': typeof TSlugConversationsRoute
  '/t/$slug/cxc': typeof TSlugCxcRoute
  '/t/$slug/fiscal-homologacion': typeof TSlugFiscalHomologacionRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/logistica': typeof TSlugLogisticaRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/procesos': typeof TSlugProcesosRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard-admin'
    | '/descargar'
    | '/login'
    | '/nueva-sucursal'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/restablecer-contrasena'
    | '/software-lavanderia-punta-cana'
    | '/software-lavanderia-santiago'
    | '/software-lavanderia-santo-domingo'
    | '/terminos'
    | '/blog/$slug'
    | '/t/$slug'
    | '/blog/'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/conversations'
    | '/t/$slug/cxc'
    | '/t/$slug/fiscal-homologacion'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/logistica'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/procesos'
    | '/t/$slug/reportes'
    | '/t/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard-admin'
    | '/descargar'
    | '/login'
    | '/nueva-sucursal'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/restablecer-contrasena'
    | '/software-lavanderia-punta-cana'
    | '/software-lavanderia-santiago'
    | '/software-lavanderia-santo-domingo'
    | '/terminos'
    | '/blog/$slug'
    | '/blog'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/conversations'
    | '/t/$slug/cxc'
    | '/t/$slug/fiscal-homologacion'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/logistica'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/procesos'
    | '/t/$slug/reportes'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard-admin'
    | '/descargar'
    | '/login'
    | '/nueva-sucursal'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/restablecer-contrasena'
    | '/software-lavanderia-punta-cana'
    | '/software-lavanderia-santiago'
    | '/software-lavanderia-santo-domingo'
    | '/terminos'
    | '/blog/$slug'
    | '/t/$slug'
    | '/blog/'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/conversations'
    | '/t/$slug/cxc'
    | '/t/$slug/fiscal-homologacion'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/logistica'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/procesos'
    | '/t/$slug/reportes'
    | '/t/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CookiesRoute: typeof CookiesRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DescargarRoute: typeof DescargarRoute
  LoginRoute: typeof LoginRoute
  NuevaSucursalRoute: typeof NuevaSucursalRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  ReportesRoute: typeof ReportesRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  SoftwareLavanderiaPuntaCanaRoute: typeof SoftwareLavanderiaPuntaCanaRoute
  SoftwareLavanderiaSantiagoRoute: typeof SoftwareLavanderiaSantiagoRoute
  SoftwareLavanderiaSantoDomingoRoute: typeof SoftwareLavanderiaSantoDomingoRoute
  TerminosRoute: typeof TerminosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TSlugRoute: typeof TSlugRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-lavanderia-santo-domingo': {
      id: '/software-lavanderia-santo-domingo'
      path: '/software-lavanderia-santo-domingo'
      fullPath: '/software-lavanderia-santo-domingo'
      preLoaderRoute: typeof SoftwareLavanderiaSantoDomingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-lavanderia-santiago': {
      id: '/software-lavanderia-santiago'
      path: '/software-lavanderia-santiago'
      fullPath: '/software-lavanderia-santiago'
      preLoaderRoute: typeof SoftwareLavanderiaSantiagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-lavanderia-punta-cana': {
      id: '/software-lavanderia-punta-cana'
      path: '/software-lavanderia-punta-cana'
      fullPath: '/software-lavanderia-punta-cana'
      preLoaderRoute: typeof SoftwareLavanderiaPuntaCanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-sucursal': {
      id: '/nueva-sucursal'
      path: '/nueva-sucursal'
      fullPath: '/nueva-sucursal'
      preLoaderRoute: typeof NuevaSucursalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargar': {
      id: '/descargar'
      path: '/descargar'
      fullPath: '/descargar'
      preLoaderRoute: typeof DescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/reportes': {
      id: '/t/$slug/reportes'
      path: '/reportes'
      fullPath: '/t/$slug/reportes'
      preLoaderRoute: typeof TSlugReportesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/procesos': {
      id: '/t/$slug/procesos'
      path: '/procesos'
      fullPath: '/t/$slug/procesos'
      preLoaderRoute: typeof TSlugProcesosRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/personal': {
      id: '/t/$slug/personal'
      path: '/personal'
      fullPath: '/t/$slug/personal'
      preLoaderRoute: typeof TSlugPersonalRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/ordenes': {
      id: '/t/$slug/ordenes'
      path: '/ordenes'
      fullPath: '/t/$slug/ordenes'
      preLoaderRoute: typeof TSlugOrdenesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/nueva-orden': {
      id: '/t/$slug/nueva-orden'
      path: '/nueva-orden'
      fullPath: '/t/$slug/nueva-orden'
      preLoaderRoute: typeof TSlugNuevaOrdenRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/logistica': {
      id: '/t/$slug/logistica'
      path: '/logistica'
      fullPath: '/t/$slug/logistica'
      preLoaderRoute: typeof TSlugLogisticaRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/login': {
      id: '/t/$slug/login'
      path: '/login'
      fullPath: '/t/$slug/login'
      preLoaderRoute: typeof TSlugLoginRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/gastos': {
      id: '/t/$slug/gastos'
      path: '/gastos'
      fullPath: '/t/$slug/gastos'
      preLoaderRoute: typeof TSlugGastosRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/fiscal-homologacion': {
      id: '/t/$slug/fiscal-homologacion'
      path: '/fiscal-homologacion'
      fullPath: '/t/$slug/fiscal-homologacion'
      preLoaderRoute: typeof TSlugFiscalHomologacionRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/cxc': {
      id: '/t/$slug/cxc'
      path: '/cxc'
      fullPath: '/t/$slug/cxc'
      preLoaderRoute: typeof TSlugCxcRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/conversations': {
      id: '/t/$slug/conversations'
      path: '/conversations'
      fullPath: '/t/$slug/conversations'
      preLoaderRoute: typeof TSlugConversationsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/configuracion': {
      id: '/t/$slug/configuracion'
      path: '/configuracion'
      fullPath: '/t/$slug/configuracion'
      preLoaderRoute: typeof TSlugConfiguracionRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/clientes': {
      id: '/t/$slug/clientes'
      path: '/clientes'
      fullPath: '/t/$slug/clientes'
      preLoaderRoute: typeof TSlugClientesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/catalogo': {
      id: '/t/$slug/catalogo'
      path: '/catalogo'
      fullPath: '/t/$slug/catalogo'
      preLoaderRoute: typeof TSlugCatalogoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/caja': {
      id: '/t/$slug/caja'
      path: '/caja'
      fullPath: '/t/$slug/caja'
      preLoaderRoute: typeof TSlugCajaRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugCajaRoute: typeof TSlugCajaRoute
  TSlugCatalogoRoute: typeof TSlugCatalogoRoute
  TSlugClientesRoute: typeof TSlugClientesRoute
  TSlugConfiguracionRoute: typeof TSlugConfiguracionRoute
  TSlugConversationsRoute: typeof TSlugConversationsRoute
  TSlugCxcRoute: typeof TSlugCxcRoute
  TSlugFiscalHomologacionRoute: typeof TSlugFiscalHomologacionRoute
  TSlugGastosRoute: typeof TSlugGastosRoute
  TSlugLoginRoute: typeof TSlugLoginRoute
  TSlugLogisticaRoute: typeof TSlugLogisticaRoute
  TSlugNuevaOrdenRoute: typeof TSlugNuevaOrdenRoute
  TSlugOrdenesRoute: typeof TSlugOrdenesRoute
  TSlugPersonalRoute: typeof TSlugPersonalRoute
  TSlugProcesosRoute: typeof TSlugProcesosRoute
  TSlugReportesRoute: typeof TSlugReportesRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCajaRoute: TSlugCajaRoute,
  TSlugCatalogoRoute: TSlugCatalogoRoute,
  TSlugClientesRoute: TSlugClientesRoute,
  TSlugConfiguracionRoute: TSlugConfiguracionRoute,
  TSlugConversationsRoute: TSlugConversationsRoute,
  TSlugCxcRoute: TSlugCxcRoute,
  TSlugFiscalHomologacionRoute: TSlugFiscalHomologacionRoute,
  TSlugGastosRoute: TSlugGastosRoute,
  TSlugLoginRoute: TSlugLoginRoute,
  TSlugLogisticaRoute: TSlugLogisticaRoute,
  TSlugNuevaOrdenRoute: TSlugNuevaOrdenRoute,
  TSlugOrdenesRoute: TSlugOrdenesRoute,
  TSlugPersonalRoute: TSlugPersonalRoute,
  TSlugProcesosRoute: TSlugProcesosRoute,
  TSlugReportesRoute: TSlugReportesRoute,
  TSlugIndexRoute: TSlugIndexRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CookiesRoute: CookiesRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DescargarRoute: DescargarRoute,
  LoginRoute: LoginRoute,
  NuevaSucursalRoute: NuevaSucursalRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  ReportesRoute: ReportesRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  SoftwareLavanderiaPuntaCanaRoute: SoftwareLavanderiaPuntaCanaRoute,
  SoftwareLavanderiaSantiagoRoute: SoftwareLavanderiaSantiagoRoute,
  SoftwareLavanderiaSantoDomingoRoute: SoftwareLavanderiaSantoDomingoRoute,
  TerminosRoute: TerminosRoute,
  BlogSlugRoute: BlogSlugRoute,
  TSlugRoute: TSlugRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
